version: "3"

x-app-common: &app-common
  depends_on:
    - database
  env_file:
    - ./.env
  volumes:
    - ./djangoapp:/djangoapp
    - ./scripts:/scripts
    - ./requirements.txt:/requirements.txt
    - static_volume:/data/static/
    - ./data/media:/data/media/
    - ./data/log:/data/log/
  environment:
    - SECRET_KEY=django-insecure
    - DEBUG=True
    - ALLOWED_HOSTS=*
    - CORS_ALLOWED_ORIGINS=*
    - CSRF_TRUSTED_ORIGINS=*
    - DB_HOST=database
    - DB_PORT=5432
    - DB_DB=app_db
    - DB_USER=app_db
    - DB_PASSWORD=app_db
    - REDIS_URL=redis://redis:6379/0

services:
  app:
    <<: *app-common
    command: "/scripts/docker/start_dev.sh"

  celery:
    <<: *app-common
    depends_on:
      - redis

  revproxy:
    build: ./nginx
    depends_on:
      - app
    volumes:
      - static_volume:/usr/src/app/static
      - ./data/media:/usr/src/app/media
    networks:
      - default
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.projectname.rule=Host(`api.projectname.com`)
      - traefik.http.routers.projectname.tls=true

  database:
    image: postgres:14.5
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_db
      - POSTGRES_PASSWORD=app_db

  redis:
    image: redis

volumes:
  static_volume:

networks:
  web:
    external: true
