version: "3.9"

x-app-common:
  &app-common
  depends_on:
    - database
    - redis
    - minio
  env_file:
    - ./.env
  environment:
    - SECRET_KEY=django-insecure
    - DEBUG=True
    - ALLOWED_HOSTS=*
    - CORS_ALLOWED_ORIGINS=*
    - CSRF_TRUSTED_ORIGINS=*

    - DB_HOST=database
    - DB_PORT=5432
    - DB_DB=app_db
    - DB_USER=app_db
    - DB_PASSWORD=app_db

    - REDIS_URL=redis://redis:6379/0

    - MINIO_ENDPOINT=minio:9000
    - MINIO_EXTERNAL_ENDPOINT=localhost:9000
    - MINIO_ACCESS_KEY=minio12345
    - MINIO_SECRET_KEY=minio12345
    - MINIO_USE_HTTPS=False

services:
  app:
    <<: *app-common
    build: .
    command: "/scripts/docker/start_dev.sh"
    volumes:
      - ./djangoapp:/djangoapp
      - ./scripts:/scripts
      - ./requirements.txt:/requirements.txt
      - ./data/media:/data/media/
      - static_volume:/data/static/
      - ./data/log-app:/data/log/

  celery:
    <<: *app-common
    build: .
    command: python -m celery -A generic_celery worker
    depends_on:
      - redis
    volumes:
      - ./djangoapp:/djangoapp
      - ./scripts:/scripts
      - ./requirements.txt:/requirements.txt
      - ./data/media:/data/media/
      - static_volume:/data/static/
      - ./data/log-celery:/data/log/

  revproxy:
    build: ./nginx
    depends_on:
      - app
    ports:
      - 8000:80
    volumes:
      - static_volume:/usr/src/app/static
      - ./data/media:/usr/src/app/media

  database:
    image: postgres:15.2
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_db
      - POSTGRES_PASSWORD=app_db

  redis:
    image: redis

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: on-failure
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ACCESS_KEY: minio12345
      MINIO_SECRET_KEY: minio12345
      MINIO_ROOT_USER: minio12345
      MINIO_ROOT_PASSWORD: minio12345

volumes:
  static_volume:
