from enum import Enum


class ErrorCode(Enum):
    INVALID_TOKEN = 'INVALID_TOKEN'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_OTP = 'INVALID_OTP'
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE'
